# Cargo configuration for dungeon project

[alias]
# Lint and format
lint = "clippy --workspace --all-targets"
fix = "clippy --workspace --fix"

# Documentation
doc = "doc --workspace --no-deps --open"

# [env]
# Note: Do not set RISC0_SKIP_BUILD here as it will interfere with risc0_build
# To skip RISC0 builds during development, use: RISC0_SKIP_BUILD=1 cargo build
