# Cargo configuration for dungeon project

[alias]
# Lint and format
lint = "clippy --workspace --all-targets --all-features"
fmt = "fmt --all"
fix = "clippy --workspace --fix"

# Documentation
doc = "doc --workspace --no-deps --open"

[env]
# Skip RISC0 guest builds by default (override with RISC0_SKIP_BUILD=0)
RISC0_SKIP_BUILD = "1"
