[package]
name = "types"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }
hex = { version = "0.4", optional = true }

[features]
default = []
serde = ["dep:serde"]
hex = ["dep:hex"]
