[package]
name = "game-core"
version = "0.1.0"
edition = "2024"

[dependencies]
bounded-vector = { version = "0.3", default-features = false }
arrayvec = { version = "0.7", default-features = false }
